language: objective-c
xcode_project: PuzzleDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: PuzzleDemo
osx_image: xcode7.3
xcode_sdk: iphonesimulator

env:
    matrix:
        - TEST_SDK=iphonesimulator8.1 SIMULATOR=iphone
        - TEST_SDK=iphonesimulator8.2 SIMULATOR=iphone
        - TEST_SDK=iphonesimulator9.0 SIMULATOR=iphone
        - TEST_SDK=iphonesimulator9.1 SIMULATOR=iphone
    script:
        - xctool test -test-sdk $TEST_SDK #-simulator $SIMULATOR
    
